import React from "react";

const Page = () => {
  return (
    <main className="font-Gotham">
      <section className="min-h-screen py-20 px-5 md:py-28 md:px-28">
        <div>
          <h1 className="text-2xl font-bold mb-3">Cookie Policy</h1>
          <p className="mb-3 font-bold">
            Influencer Marketing Hub Cookie Policy 
          </p>
          <p className="mb-3 font-bold">Last Updated 3 May 2021</p>
          This website 
          <a
            href="https://influencermarketinghub.com"
            className="text-[#FD0053]"
          >
            https://influencermarketinghub.com
          </a>
           (the “Website”) uses cookies. We use cookies to personalise content
          and ads, to provide social media features and to analyse our traffic.
          We also share information about Your use of the Website with Our
          social media, advertising and analytics partners who may combine it
          with other information that You’ve provided to them or that they’ve
          collected from Your use of their services. Who is responsible for
          cookies on the Website? The data controller that is responsible for
          the processing of personal data through the Website, including placing
          first-party cookies, is Influencer Marketing Hub by Clifton
          Technologies APS having a registered business address at 68
          Flaesketorvet, 1711, Copenhagen, Denmark, and a  registration number
          36428767 (“We,” “Us,” or “Our”).
          <h2 className="text-2xl font-bold my-3">
            What should You know about cookies?
          </h2>
          Cookies are small text files that can be used by websites to make a
          user&apos;s experience more efficient. When you visit a website, that
          website may send a cookie to your browser. Subsequently, the browser
          may store the cookie on your computer or mobile device for some time
          (cookie expiration date depends on its type). Cookies are used to
          recognise Your device and collect certain information about Your use
          of websites. Thus, over time, cookies allow websites to “remember”
          Your actions and preferences. There are several types of cookies,
          namely, (i) persistent cookies, which remain valid until deleted by
          You, (ii) cookies that remain valid until their expiration date, and
          (iii) session cookies that are stored on a web browser and remain
          valid until the moment the browser is closed. Cookies may also be (i)
          first-party cookies (set by the original website itself) and (ii)
          third-party cookies (placed by third-party websites).
          <h2 className="text-2xl font-bold my-3">Your consent to cookies</h2>
          The law states that we can store cookies on your device if they are
          strictly necessary for the operation of this Website. For all other
          types of cookies we need your permission. We will ask for your
          permission by using a cookie consent banner. If you do not consent to
          our use of non-essential cookies, we will serve you essential cookies
          only. You can withdraw your consent at any time by adjusting your
          cookie settings on your browser or cookie banner.  
          <h2 className="text-2xl font-bold my-3">Google Analytics</h2>
          To analyse your use of the Website, We use Google Analytics, the
          business analytics service provided by Google LLC located in the
          United States (“Google”), in addition to other analytics service
          providers. Google generates statistical information by means of
          cookies and creates reports about your use of the Website. The cookies
          served by Google Analytics are anonymous first-party cookies (please
          refer to the table below for more information) that do not allow Us to
          identify You in any manner. The information generated by cookies will
          be transmitted to and stored by Google on servers in the United
          States. To ensure your privacy, Your IP address will be anonymised and
          Google will not combine Your IP address with other information Google
          holds about You. Thus, Google will not be able to identify You. In
          certain cases (e.g., when required by law or when third parties
          conduct services on behalf of Google), Google may transfer the
          information to third parties. For more information about Google
          Analytics’ privacy practices, please visit
           https://support.google.com/analytics/answer/6004245. If You would
          like to opt out from Google Analytics, you can do so by installing a
          Google Analytics opt-out browser add-on available at
           https://tools.google.com/dlpage/gaoptout?hl=en. 
          <h2 className="text-2xl font-bold my-3">
            Interest-based advertising
          </h2>
          You may encounter targeted interest-based advertising based on Your
          use of the Website and other websites on the Internet because We
          collect your Google Advertising ID. Where necessary, We will seek Your
          consent. You can control how such advertising is shown to You or
          opt-out from targeted advertising by consulting the guide powered by
          the Digital Advertising Alliance available
          at https://youradchoices.com. For more information on opting-out from
          advertising features on Your device, please visit
           https://www.networkadvertising.org .
          <h2 className="text-2xl font-bold my-3">What cookies do We use? </h2>
          This Website uses different types of cookies. Some cookies are placed
          by third-party services that appear on Our pages.
          <h2 className="text-2xl font-bold my-3">Necessary</h2>
          Necessary cookies are required to enable the basic features of this
          site, such as providing secure log-in or adjusting your consent
          preferences. These cookies do not store any personally identifiable
          data.
          <img src="/cookies/table1.png" alt="" className="my-3 w-full" />
          <h2 className="text-2xl font-bold my-3">Functional</h2>
          Functional cookies help perform certain functionalities like sharing
          the content of the website on social media platforms, collecting
          feedback, and other third-party features.
          <img src="/cookies/table2.png" alt="" className="my-3 w-full" />
          <h2 className="text-2xl font-bold my-3">Analytical</h2>
          cookies are used to understand how visitors interact with the website.
          These cookies help provide information on metrics such as the number
          of visitors, bounce rate, traffic source, etc.
          <img src="/cookies/table3.png" alt="" className="my-3 w-full" />
          <h2 className="text-2xl font-bold my-3">Advertisement</h2>
          Advertisement cookies are used to provide visitors with customized
          advertisements based on the pages you visited previously and to
          analyze the effectiveness of the ad campaigns.
          <img src="/cookies/table4.png" alt="" className="my-3 w-full" />
          <h2 className="text-2xl font-bold my-3">Uncategorized</h2>
          Other uncategorized cookies are those that are being analyzed and have
          not been classified into a category as yet.
          <img src="/cookies/table5.png" alt="" className="my-3 w-full" />
          <h2 className="text-2xl font-bold my-3">Contact</h2>
          If You have any questions about our cookies, please contact us:
          <br />
          <b>Email:</b>{" "}
          <a
            href="mailto:hello@influencermarketinghub.com"
            className="text-[#FD0053]"
          >
            hello@influencermarketinghub.com
          </a>
          <br />
          <b>Address:</b> Clifton Technologies ApS, 68 Flaesketorvet, 1711,
          Copenhagen, Denmark 
        </div>
      </section>
    </main>
  );
};

export default Page;
